## Lesson 2 — PyTorch Essentials

### 1. Tensor Basics

In [12]:
#A tensor generalizes scalars, vectors and matrices to arbitrary dimensions.
scalar = torch.tensor(5)
vector = torch.tensor([4, 5, 6])
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
three_d = torch.zeros((2, 3, 4))

print(scalar)
print(vector)
print(matrix)
print(three_d)

tensor(5)
tensor([4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [13]:
print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print(three_d.shape)

torch.Size([])
torch.Size([3])
torch.Size([3, 3])
torch.Size([2, 3, 4])


In [16]:
# Creating different tensors

print(torch.zeros(2, 3))
print(torch.ones(2, 3))
print(torch.rand(2, 3)) #random numbers from 0 to 1
print(torch.randn(2, 3)) # random numbers from a standard normal distribution.

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0436, 0.5426, 0.9828],
        [0.7244, 0.3600, 0.0824]])
tensor([[-0.3277,  0.3524, -0.4327],
        [ 0.8991,  0.1684, -0.0902]])


In [19]:
print(torch.arange(0, 10, 2)) #Give me values with this step

tensor([0, 2, 4, 6, 8])


In [20]:
print(torch.linspace(0, 1, 5)) #Give me this many evenly spaced values.

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [22]:
# EXAMPLE
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

# IMPORTANT PROPERTIES
print("Shape:", x.shape)
print("Size:", x.size())
print("Data type:", x.dtype)
print("Device:", x.device)

Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Data type: torch.int64
Device: cpu


### 2. Indexing & Slicing

In [27]:
#INDEXES
x = torch.tensor([
    [10, 20, 30], # 0
    [40, 50, 60], # 1
    [70, 80, 90]  # 2
])

print(x[1,2])
print(x[0])
print(x[:, 1])
print(x[0:2, 1:3])

tensor(60)
tensor([10, 20, 30])
tensor([20, 50, 80])
tensor([[20, 30],
        [50, 60]])


### 3. Reshaping

In [30]:
# RESHAPE
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

y = x.reshape(4, 3)

print(y)
print(y.shape)

print(x.reshape(-1))


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [32]:
# FLatten () -- converts tensor into 1D long tensor
print(x.flatten())

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


### EXERCISES:

In [40]:
# EXERCISE

a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(a.shape)
print(a[1, 1])
print(a[:, 0]) # print first column

p = a.reshape(3, 2)
print(p)

print(a.flatten())

torch.Size([2, 3])
tensor(5)
tensor([1, 4])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])
